#include <Utils/macros.h>

#include "../src/Graphics/SRSL/Lexer.cpp"
#include "../src/Graphics/SRSL/LexicalTree.cpp"
#include "../src/Graphics/SRSL/MathExpression.cpp"
#include "../src/Graphics/SRSL/LexicalAnalyzer.cpp"
#include "../src/Graphics/SRSL/Shader.cpp"
#include "../src/Graphics/SRSL/ICodeGenerator.cpp"
#include "../src/Graphics/SRSL/PseudoCodeGenerator.cpp"
#include "../src/Graphics/SRSL/GLSLCodeGenerator.cpp"
#include "../src/Graphics/SRSL/RefAnalyzer.cpp"
#include "../src/Graphics/SRSL/AssignExpander.cpp"
#include "../src/Graphics/SRSL/TypeInfo.cpp"
#include "../src/Graphics/SRSL/Evaluator.cpp"
#include "../src/Graphics/SRSL/PreProcessor.cpp"
#include "../src/Graphics/SRSL/ShaderVariables.cpp"